export const trainingActionConstants = {
  FETCH_TRAINING_LIST: 'FETCH_TRAINING_LIST',
  FETCH_TRAINING_ENTITY: 'FETCH_TRAINING_ENTITY',
  TRAINING_CONTENT_CHANGED: 'TRAINING_CONTENT_CHANGED',
  SAVE_TRAINING: 'SAVE_TRAINING',
};
